---
abstract: 'Git Support for YamlTime'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: YamlTime-Git
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  YamlTime: '0.14'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/yamltime-git-pm/issues
  homepage: https://github.com/ingydotnet/yamltime-git-pm
  repository: https://github.com/ingydotnet/yamltime-git-pm.git
version: '0.05'
